# Welcome to Jekyll!
#

# Site settings
title: Kay McMonigal
description: |
  Incoming assistant professor
  University of Alaska Fairbank
  College of Fisheries and Ocean Sciences
owner: Kayleen McMonigal # or company name
author: Kay McMonigal
author: K McMonigal
author: KT McMonigal
author: Kayleen McMonigal
first_published: 2016 # if migrating another site, the year of your first publish
email: kmcmonigal@rsmas.miami.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kmcmonigal.github.io" # the base hostname & protocol for your site
social:
  #twitter: #https://twitter.com/<username>
  github: https://github.com/kayleenmc
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: ktmcmonigal@alaska.edu
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
gems:
  - jekyll-seo-tag
